### ISSUE TITLE
Add Manifest details to PWA page

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#107]
We should show the data from the Manifest on the PWA detail page. We can either show it as a beautified JSON or find another way of visualizing the data.

**Comment by andreban** [comment]
I'm wondering the best way to show the raw manifest. This doesn't look very good:
![Uploading Screen Shot 2016-09-07 at 1.55.15 PM.png…]()

@ithinkihaveacat @juliantoledo Ideas?

**Comment by ithinkihaveacat** [comment]
I think that's okay, especially for MVP—? As an alternative, could just link to our copy?

**Comment by juliantoledo** [comment]
Yes, for MVP is great. Let's do some CSS later next week.
