### ISSUE TITLE
Behave similarly to offline when server is not online.

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#109]
Currently offline deactivates parts of the UI (add, edit, delete), however if the browser is online but the server is not those parts are enable.
- [ ] Handle DB offline (Server and browser online)
- [ ] Handle Server offline (browser online)

**Comment by ithinkihaveacat** [comment]
This is to deal with the situation that the browser can connect to the server, but for some reason the server can't connect to GCP or its datastore? You think we should do something more than displaying internal server errors in this case?

**Comment by andreban** [comment]
Speaking in a more generic way, we need to account for the LieFi case (eg: timeout for resources form the server).

**Comment by juliantoledo** [comment]
yes, that and that the server may be down but the user has connectivity.
