### ISSUE TITLE
Remove ability to edit/delete PWAs

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#114]
![screen shot 2016-09-05 at 5 37 43 pm](https://cloud.githubusercontent.com/assets/51244/18253787/8a0c9084-738f-11e6-996e-d3954099fe23.png)

- [ ] From the web interface (for all users)
- [ ] From the API

**Comment by andreban** [comment]
We should also remove PWA submission from the API, since we require login.
