### ISSUE TITLE
Update Lighthouse info daily/weekly

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#121]
We need to queue Lighthouse requests to update each PWAs score daily/weekly.

For tasks we need to test:
- [ ] bee-queue or kue
- [ ] Google Tasks Queues [https://github.com/google/google-api-nodejs-client/blob/master/apis/taskqueue/v1beta2.js](url)
- [ ] Cron/Scheduling

**Comment by addyosmani** [comment]
If you run into any trouble getting batch Lighthouse processing for PWAs setup, feel free to reach out. @brendankenny has been exploring a local version of this and I started exploring a super rough version of this a week ago. Note that some of Lighthouse's tests when run headless may not be 100% accurate atm (e.g Service Worker/offline tests don't always score the way they do when run from the extension or command line).

**Comment by brendankenny** [comment]
yes, I'm not sure about the exact status these days, but at least recently Service Workers were barely functional at all in headless Chrome

**Comment by juliantoledo** [comment]
@addyosmani @brendankenny, We have been working with @crhym3, he created a docker image that runs Lighthouse with headless Chrome. We found few differences in the score/results, we may need help to improve that in the long term.

**Comment by brendankenny** [comment]
Ah, yes, we had a thread a while back with @crhym3 over issues with headless he was running into. I think fundamentally it's still very much a work in progress and it's still a little hard to predict what won't be working and how that'll manifest when you run it :)

The good news is (I believe) Alex has said he can switch his setup over to using real Chrome if need be, so if the headless bugs pile up too deep we can always go with that.

**Comment by x1ddos** [comment]
I'm updating server-side lighthouse version + headless today, hoping things will get better.
Heaving issue with re-compiling headless_shell though, seems to be broken.
