### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#133]
Add GA to all pages. 

**Production**

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82966500-2', 'auto');
  ga('send', 'pageview');
</script>
```

**Development**

```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82966500-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by juliantoledo** [comment]
Development:
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82966500-1', 'auto');
  ga('send', 'pageview');

</script>`

Production:
`<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82966500-2', 'auto');
  ga('send', 'pageview');

</script>`

**Comment by andreban** [comment]
The difference between those codes is only the UA code. We could add a helper function to replace the UA code with the correct one. What is the best way to differentiate between production / development? @ithinkihaveacat @juliantoledo @amedina

**Comment by ithinkihaveacat** [comment]
@andreban To distinguish between production/development I think we should ultimately use the `NODE_ENV` environment variable. ([Express already uses this](http://expressjs.com/en/advanced/best-practice-performance.html#in-environment)—just set it to `production` or `development` as appropriate.)

So I think the steps would be:

1. Add to `config.json` and `config.js`, arrange for the default to be `development`.
2. Then either:
  1. Make `window.__config.NODE_ENV` available on the front end directly, and get the front-end to choose the appropriate GA id.
  2. Make `window.__config.GA` (or similar) available on the front end, and set via backend.

See the `configstring` section of `app.js` and `__config` in `head.hbs` to see how this works. Actually probably would have been better to get rid of the `configstring` name and just use `__config` everywhere (for grepability)—maybe you could change this while you're there? (I did this originally.)
