### ISSUE TITLE
Create a logo for Gulliver

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#135]
- Create a logo icon for Gulliver and add it to the page headers and as an icon to manifest.json

**Comment by juliantoledo** [comment]
I am testing how this one looks in different places:
![android-chrome-512x512](https://cloud.githubusercontent.com/assets/1920764/18627017/d7ef130c-7e58-11e6-9f6a-a9fc53ef4e16.png)

**Comment by ithinkihaveacat** [comment]
Are you using https://realfavicongenerator.net/? That provides decent previews and also writes all the awkward meta tags…

**Comment by juliantoledo** [comment]
@ithinkihaveacat yes, that is what I used, great tool.

I also ran their https://realfavicongenerator.net/favicon_checker, that tool told me to add a missing favicon.ico to the root.
