### ISSUE TITLE
Improve PWA Detail layout on Mobile

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#137]
Some of the content is being rendered outside the viewport on mobile.

<img width="386" alt="screen shot 2016-09-13 at 4 28 19 pm" src="https://cloud.githubusercontent.com/assets/1733592/18480040/1e97b98c-79cf-11e6-9af4-d1da6ebe4953.png">

**Comment by juliantoledo** [comment]
This is part of  #140, I will do some quick changes before we add Tabs for Manifest and Lighthouse.
