### ISSUE TITLE
Improve logging?

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#147]
What logging does GCP provide? e.g. do `console.log()` messages get logged somewhere? Do we need to add anything else?

**Comment by juliantoledo** [comment]
We could try this:
https://cloud.google.com/nodejs/getting-started/logging-application-events

**Comment by juliantoledo** [comment]
I will work on this asap, I just found that we need it sooner than later.

**Comment by andreban** [comment]
Although anything that's printed to console.log or console.error is available in the Google Cloud Platform console.

**Comment by juliantoledo** [comment]
I found few 500 errors and I could not find the console.log info

**Comment by andreban** [comment]
Can you reproduce locally and check if a message is being printed to the console?
