### ISSUE TITLE
Display detailed Lighthouse results

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#148]
We currently show the Lighthouse score on the detail page. We should also display the full Lighthouse results. (And ensure they're linkable/sharable.)

(As suggested by @slightlyoff.)

**Comment by juliantoledo** [comment]
Should we store the full HTML lighthouse report and link to it?
We are currently parsing it and storing a subset.

**Comment by juliantoledo** [comment]
I finished the server side part, we now need to improve the Detail Page UI and add a tab for Lighthouse.

**Comment by juliantoledo** [comment]
Moved to #140
