### ISSUE TITLE
Add a Web App Manifest validator

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#149]
We should add a Web App Manifest validator.

For example: https://web.telegram.org/manifest.json is not valid because it does not have an array of icons.

**Comment by andreban** [comment]
Their icons section looks like this:
```
  "icons": {
    "16": "img/icons/icon16.png",
    "32": "img/icons/icon32.png",
    "60": "img/icons/icon60.png",
    "64": "img/icons/icon64.png",
    "90": "img/icons/icon90.png",
    "128": "img/icons/icon128.png"
  }
```

I think we're expecting something like the following:
```
  "icons": [{
    "src": "/icon/web_hi_res_512.png",
    "sizes": "512x512",
    "type": "image/png"
  }]
```

Is their approach valid? If it is we should support. Otherwise, we can test if `icons` is an Array before using it.

**Comment by juliantoledo** [comment]
Seems valid:
https://developer.chrome.com/extensions/manifest/icons

I wonder if we have a good way to validate the manifest.json formatting.

**Comment by ithinkihaveacat** [comment]
We could probably use https://github.com/mounirlamouri/manifest-validator
(written by a Googler).

**Comment by juliantoledo** [comment]
Seems like the telegram one is for the Chrome Web Store and not at Web App Manifest.

The icons need to be an array:
https://w3c.github.io/manifest/#icons-member

Let's try that one @ithinkihaveacat

**Comment by brendankenny** [comment]
Lighthouse has a manifest parser that we forked from the one from mlamouri and have slowly updated for more corner cases/correctness and added tests: https://github.com/GoogleChrome/lighthouse/blob/master/lighthouse-core/lib/manifest-parser.js

The format it spits out is a little confusing, because rather than log any errors to console, at every step into the parsed manifest object it gives the parsed `value` but also an error string (`debugString`). In practice you end up writing a lot of things like manifest.value.icons.value[0].value.src.value, but I can write a quick converter that would just spit out what the parsed value ends up being :)

**Comment by brendankenny** [comment]
as an example, for your bad icons example, 

```js
  {"icons": {
    "16": "img/icons/icon16.png",
    "32": "img/icons/icon32.png",
    "60": "img/icons/icon60.png",
    "64": "img/icons/icon64.png",
    "90": "img/icons/icon90.png",
    "128": "img/icons/icon128.png"
  }}
```
gives a parsed response of (cutting out other manifest fields):
```js
{
    "icons": {
      "value": [],
      "debugString": "ERROR: 'icons' expected to be an array but is not."
    }
}
```

whereas the correct version
```js
{
  "icons": [{
    "src": "/icon/web_hi_res_512.png",
    "sizes": "512x512",
    "type": "image/png"
  }]
}
```

gives (again, cutting out other fields) the much more verbose but useful:
```js
{
  "icons": {
    "value": [{
      "value": {
        "src": {
          "value": "https://example.com/icon/web_hi_res_512.png"
        },
        "type": {
          "value": "image/png"
        },
        "density": {
          "value": 1
        },
        "sizes": {
          "value": [
            "512x512"
          ]
        }
      }
    }]
  }
}
```
(note that this assumes a manifest located at example.com)

And then we could add a simple utility function that would pare that back down to

```js
{
  "icons": [{
    "src": "https://example.com/icon/web_hi_res_512.png",
    "type": "image/png",
    "density": 1,
    "sizes": [
      "512x512"
    ]
  }]
}
```
which is how the browser interprets that input manifest.

**Comment by ithinkihaveacat** [comment]
@brendankenny Thanks for the heads up! I'll have a look at this.

**Comment by ithinkihaveacat** [comment]
See https://github.com/GoogleChrome/gulliver/pull/165.
