### ISSUE TITLE
Remove login/logout button

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#171]
I was showing @sebastianbenz the site today, and he noted that the login/logout buttons don't add much at the moment, and that the identity login/logout functionality should be folded into the "add PWA" flow, rather than prominently displayed on every page of the site.

**Comment by andreban** [comment]
On the other hand, if the user **is** logged-in, it makes sense to show it on every page of the site.

**Comment by juliantoledo** [comment]
I was actually thinking about that few days ago, I think is a good idea. However, soon after MVP, I think we should allow users to choose their favorite PWAs and then we would need to add it again.

**Comment by ithinkihaveacat** [comment]
That's true, as soon as we add more customization we'll need it again.

How about we leave this as an issue, but not move it into the MVP milestone. If we have loads of time we can implement. (And then revert in a few weeks or whatever when we need it again.)

**Comment by juliantoledo** [comment]
+1

**Comment by amedina** [comment]
SGTM
