### ISSUE TITLE
Security review: user-generated content

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#180]
We display UGC on Gulliver (the manifest itself and lighthouse results) so we need to make sure you can't do anything bad with this.

We should use a security-minded library for escaping, and probably also add content-security-policy headers to prevent inline JS from being executed. (And we actually have some inline JS at the moment, so this will need to be removed.)

This will probably also affect #179, which does syntax highlighting. (We might not be able to do this.)

**Comment by juliantoledo** [comment]
I will probably usa https://github.com/cure53/DOMPurify

For #179, Would moving the syntax highlighting to the server side help?
