### ISSUE TITLE
Detail page: manifest section does not display original manifest

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#181]
The manifest section of the detail page does not display the original manifest—I think it's a lightly transformed version we use internally. We probably should display the original manifest here, or else make it clear that it's different. (Reformatting is probably okay/desirable.)

<img width="645" alt="screen shot 2016-09-23 at 9 16 54 am" src="https://cloud.githubusercontent.com/assets/51244/18778932/c069c5ec-816e-11e6-94dc-12cf224ef4e0.png">

Compared to the original at <https://www.terra.com.br/manifest-br.json>, this contains a `url` property, and `icons` is a bit mangled.

**Comment by juliantoledo** [comment]
I guess the values get shifted around with the JSON.parse() and JSON.stringify() when we get it and store it in the DB. We need to investigate where exactly.

**Comment by amedina** [comment]
We can put a link to the original manifest so the user gets the original.

**Comment by amedina** [comment]
Would that be a good approach? We has it but I removed it because the
usability looked weird.

**Comment by juliantoledo** [comment]
let's investigate first if we can keep it as the original somehow.

**Comment by amedina** [comment]
Looking at the Manifest JSON coming from datastore it is identical to the one being highlighted; both have a 'url' key and the icons are the same.

**Comment by juliantoledo** [comment]
We would need to store the raw string of the manifest in the DB.

**Comment by ithinkihaveacat** [comment]
I'm pro storing the raw string (makes debugging various manifest problems easier).
