### ISSUE TITLE
Make it easier for people to add new PWAs on mobile

### ISSUE THREAD

**Issue by adewale** [GoogleChrome/gulliver#190]
If the user is on a mobile device it's really hard to go from a URL like: https://sprinkle.works and find the URL of the manifest: https://sprinkle.works/manifest.json

Therefore:
- let users provide a URL to a web page
- fetch the web page and look for an element like `<link rel="manifest" href="/manifest.json">`
- identify the URL for the manifest
- submit that manifest's URL

**Comment by andreban** [comment]
@ithinkihaveacat had some info about being possible to add the manifest using Javascript instead of the link rel tag. Can you add the details on how it works here?

**Comment by ithinkihaveacat** [comment]
You can inject the entire `<link>` element via JS. http://pureformulas.com does this. (Lighthouse also seems to detect it correctly though not sure how it's doing it. The manifest URL also doesn't seem to be available in the report, though I guess this can be added.)
