### ISSUE TITLE
Safari does not support CSP nonce

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#193]
Safari 9 does not support the "nonce" system of executing `<script>` inline. (Via manual testing and [this SO answer](http://stackoverflow.com/a/32799341/11543).)

**Comment by juliantoledo** [comment]
We should test if this is true for Chrome/Firefox "if a nonce is present then 'unsafe-inline' is ignored.", if so, we can add 'unsafe-inline' for Safari.

**Comment by ithinkihaveacat** [comment]
I ended up completely getting rid of the nonces (in #197).
