### ISSUE TITLE
JS does not execute in Safari 9

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#194]
Safari [does not support arrow functions](http://caniuse.com/#feat=arrow-functions).

**Comment by ithinkihaveacat** [comment]
We can fix this by either:

- manually fixing `gulliver.js` (either actually manually, or running through babel or tsc once by hand)
- adding in a build process

**Comment by ithinkihaveacat** [comment]
Should be fixed by https://github.com/GoogleChrome/gulliver/pull/195.

**Comment by juliantoledo** [comment]
I added /public/js/gulliver.js to .eslintignore
because the generated file uses tabs instead of spaces.

**Comment by ithinkihaveacat** [comment]
Seems fixed. I'm getting pushed to install Safari 10 too, so right about time!
