### ISSUE TITLE
Lighthouse score fails to score HTTPS properly

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#204]
At the moment our Lighthouse score fails to score HTTPS properly, the reason is that we are using a server side version of Lighthouse called Moonlight that has a bug on the HTTPS scoring.

We are working with the Lighthouse team to solve it soon.

**Comment by x1ddos** [comment]
@juliantoledo can you assign this to me? I'm working on updating server-side version. Hopefully it'll fix the issue.

**Comment by juliantoledo** [comment]
Sure @x1ddos, thank you!

**Comment by x1ddos** [comment]
It feels like an issue with headless chrome after all.
I posted a question to headless-dev: https://groups.google.com/a/chromium.org/d/topic/headless-dev/RqxZAsYra0Y/discussion

**Comment by adewale** [comment]
See: https://bugs.chromium.org/p/chromium/issues/detail?id=609394 for the underlying cause.

**Comment by abdonrd** [comment]
Any news?

**Comment by x1ddos** [comment]
@abdonrd The underlying issue has been finally resolved a few days ago. I will pull in the changes and see whether it fixes this bug.

Will update this thread soon.

**Comment by abdonrd** [comment]
Nice! Thanks @x1ddos!

**Comment by x1ddos** [comment]
Good news, https://airhorner.com/ now scores 97/100 on moonlight and has passes HTTPS checks:

![image](https://cloud.githubusercontent.com/assets/25405/20708144/eed55ee2-b62e-11e6-883f-f0f437cea380.png)

**Comment by abdonrd** [comment]
Nice! 🎉

**Comment by juliantoledo** [comment]
@x1ddos Great!!! I will update our server.

**Comment by x1ddos** [comment]
@juliantoledo I'll start the OSS process for moonlight.

**Comment by juliantoledo** [comment]
@x1ddos Thank you for your work on moonlight!

Deployed your new version to our server, it will take about 1 hour to score all PWAs again.

**Comment by abdonrd** [comment]
Yay! Thanks @juliantoledo!

**Comment by abdonrd** [comment]
Why the differences in Gulliver and Lighthouse extension?

Gulliver: 91
https://pwa-directory.appspot.com/pwas/5761645611581440

Lighthouse extension: 97
![screen shot 2016-12-02 at 12 20 51](https://cloud.githubusercontent.com/assets/1007051/20832289/d2260abe-b889-11e6-86ef-db564670fae5.png)

**Comment by juliantoledo** [comment]
@abdonrd we use a version of Lighthouse built on Headless Chromium which enables it to run as a server app, for that reason our Lighthouse score and report may deviate from the standard Lighthouse Chrome extension. We are trying to get as close as possible, the major issue we had was the HTTPS detection, but we still need to look into other broken signals.

**Comment by adewale** [comment]
Please file bugs for any differences you find.
