### ISSUE TITLE
Telegram fails to be added

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#214]
Manifest Url: https://web.telegram.org/manifest.json

<img width="397" alt="screen shot 2016-10-11 at 1 38 53 pm" src="https://cloud.githubusercontent.com/assets/1733592/19270478/2311a438-8fb8-11e6-848b-20d242706337.png">

**Comment by juliantoledo** [comment]
@andreban Their manifest is not a valid Web App Manifest. I think this is working as intended.

**Comment by juliantoledo** [comment]
This is working as intended, 'icons' should be an array to be a valid manifest.

**Comment by juliantoledo** [comment]
This PR will improve the error shown to the user
https://github.com/GoogleChrome/gulliver/pull/289
