### ISSUE TITLE
Indicate if no lighthouse score is available

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/gulliver#225]
Before we have a first lighthouse score we show the score as 0. This can be misleading. Either show `-`, `n/a` or maybe an icon, e.g. [this](https://design.google.com/icons/#ic_hourglass_full).

**Comment by juliantoledo** [comment]
Great idea. Thank you @sebastianbenz

**Comment by ithinkihaveacat** [comment]
I suppose a push notification would be nice, once the score is available
too.

**Comment by juliantoledo** [comment]
It takes about 1 minute to get the score, let's open an issue to start building notifications in general.
