### ISSUE TITLE
Comparing performances

### ISSUE THREAD

**Issue by kul3r4** [GoogleChrome/gulliver#226]
https://pwa-directory.appspot.com/pwas/5692592335355904 shows the actual performances. Could Gulliver be used to decide if, making a change, the page is definitively faster? For doing that, it would need a way to specify 2 different URLs. This way it would help developers to be more confident that when making the suggested changes, which results they will see.

**Comment by juliantoledo** [comment]
@kul3r4 Interesting, this would be a kind of A/B testing, I think it would be easier for the developer to run Lighthouse directly. On the other hand, we are keeping track of the Lighthouse scores over time and that could be useful for tracking two versions.

@andreban @ithinkihaveacat thoughts?

**Comment by ithinkihaveacat** [comment]
I think for the moment we should keep Gulliver focused on the directory aspect. Hopefully services will spring up that make it easy to compare difference versions of the same site for perf testing.
