### ISSUE TITLE
Offer lighthouse re-scan button for a PWA

### ISSUE THREAD

**Issue by sebastianbenz** [GoogleChrome/gulliver#227]
Questions:

* how to de-bounce requests?
* how to indicate in UI that re-scan is scheduled?

**Comment by juliantoledo** [comment]
We are currently updating PWAs once a day, if we add a re-scan button maybe we should limit the number of re-scans to one per 10-60min, to avoid hitting the lighthouse server too often.

**Comment by juliantoledo** [comment]
We will keep using the once a day cron for now.
