### ISSUE TITLE
Support sharing of URLs

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#229]
Via `navigator.share()` if available, with fallback to our own UI; see [Introducing the Web Share API](https://developers.google.com/web/updates/2016/10/navigator-share).

Fallback will probably want to use [Cut and Copy commands](https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en). (Which [possibly works on iOS too](http://caniuse.com/#feat=document-execcommand).)

**Comment by ithinkihaveacat** [comment]
(I've applied for an origin trial token.)

**Comment by ithinkihaveacat** [comment]
Also probably useful: https://github.com/zenorocha/clipboard.js

**Comment by samthor** [comment]
Unfortunately `navigator.share` [is no longer being offered via Origin Trial](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/kSEGnTX2dsA), but may get launched properly in the future.

**Comment by ithinkihaveacat** [comment]
I think the origin trial was the only way to invoke the system share dialog on any platform. Without it, the best we can do is clipboard access.
