### ISSUE TITLE
Add support for manifest "description"

### ISSUE THREAD

**Issue by kenchris** [GoogleChrome/gulliver#232]
This will probably be quite popular when MS starts surfacing PWAs in the Windows Store, so better add it now to make people aware of it. @boyofgreen

**Comment by juliantoledo** [comment]
@kenchris We are currently using the description field in the manifest itself. Do you mean that one or something additional when adding a PWA?

**Comment by kenchris** [comment]
Maybe I missed it in the list then. I saw checks for other fields

**Comment by kenchris** [comment]
Ah it is just not in the audits
