### ISSUE TITLE
The directory shows large amounts of no contents on desktop, yet pages items

### ISSUE THREAD

**Issue by kenchris** [GoogleChrome/gulliver#234]
My screen can fit many more apps and yet the app splits them into various pages with few items.

Lazy loading into one "infinite" list is probably a better UI paradigm

**Comment by juliantoledo** [comment]
@kenchris great feedback and idea, thank you!

**Comment by juliantoledo** [comment]
We want to implement a Material Design UI, we will change it then.

**Comment by juliantoledo** [comment]
I have increased the number of PWAs per page for now, we will change it later to an infinite scroll.
