### ISSUE TITLE
Your https detection seems to be broken

### ISSUE THREAD

**Issue by alipattsev** [GoogleChrome/gulliver#235]
Hi,
Looks like you're saying "false" for "site is on https" for all the examples, while some clearly are on https. Am I missing something or is something broken?

**Comment by juliantoledo** [comment]
Hi @alipattsev 

Thank you for reporting it, we found a problem in Chrome Headless Shell that is causing this problem:
https://github.com/GoogleChrome/gulliver/issues/204

We need to fix it soon, I will close this issue and keep the other one open.

**Comment by juliantoledo** [comment]
Duplicated of https://github.com/GoogleChrome/gulliver/issues/204
