### ISSUE TITLE
Implement push notifications

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#237]
We will start with push notifications for:
- [x] Subscribe to new PWAs

**Comment by adewale** [comment]
It would be great to have a settings page where the user is given a list of events that they'd like to be notified about. Then when one of those events happens the user would get notified. This would avoid being spammy.

**Comment by juliantoledo** [comment]
@adewale +1 great idea.

**Comment by andreban** [comment]
#259 
#257
