### ISSUE TITLE
Improve PWA-related analytics

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#239]
We should improve our analytics:
- [x] Track usages of add to home screen
- [x] Track launches from the home screen
- [x] Distinguish between offline/offline views (offline views are tracked, but I'm not sure if we can currently distinguish between the two in GA)
- [ ] Publish article about how this all works

**Comment by andreban** [comment]
#246 will enable us to check launches from home screen on Google Analytics.

**Comment by andreban** [comment]
One more thing that I would like to track is cached pageviews. What do you think? We can then check how effective the caching strategy is and how future changes will affect.

**Comment by andreban** [comment]
#250 tracks usages of A2H.
