### ISSUE TITLE
URL Fragment Issue?

### ISSUE THREAD

**Issue by developit** [GoogleChrome/gulliver#249]
Hi there - I think you noted this on Twitter, but it looks like there is an issue when a manifest's start_url contains a hash value. 'Preact' is https://preactjs.com/#home=true and it fails to run lighthouse. 

I'll probably remove the hash, but I thought it was worth looking into.

**Comment by paulirish** [comment]
hey jason, i'm having overall trouble connecting to the site, especially under HTTPS. 

![image](https://cloud.githubusercontent.com/assets/39191/20249595/6dd776ec-a9b1-11e6-85ae-52a591880f60.png)


can you reproduce any of this?

**Comment by paulirish** [comment]
ah we missed the *js*, yeah?

https://preactjs.com/#home=true

**Comment by developit** [comment]
Ack! That would be autocorrect (somehow my phone hasn't learned "preactjs.com" yet, a little odd).

I'd like to change the start_url since I'm not using the fragment at all, but yup that's what it currently is.  Wasn't sure if that was a Lighthouse thing, or gulliver.

**Comment by juliantoledo** [comment]
@developit I will take a look at the # issue, I noticed you already removed it from your start_url.

**Comment by developit** [comment]
I did! sorry 😅
