### ISSUE TITLE
Add support for Icons using Data URIs

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#255]
Add support for Icons using Data URIs, for example:
https://mobile.twitter.com/manifest.json

Uses:
"icons":[{"src":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA....

**Comment by ithinkihaveacat** [comment]
Ouch :-(

**Comment by juliantoledo** [comment]
@ithinkihaveacat already working at #256 :)
