### ISSUE TITLE
Lyft is not up-to-date

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/gulliver#275]
https://pwa-directory.appspot.com/pwas/5743346702090240 shows HTTPS and SW as false (!) and the score as 32 (it's now 87).

Is the cron job okay?

**Comment by andreban** [comment]
The manifest for Lyft recorded on PWA-Directory is https://ride.lyft.com/manifest.json, but it's 404'ing. Could you point us to the correct manifest?

**Comment by dandv** [comment]
https://ride.lyft.com/static/manifest.json

**Comment by andreban** [comment]
Even with the new manifest, the updated score is 47. One of the things is that it seems that https://ride.lyft.com is redirecting to https://www.lyft.com/auth?next=https%3A//www.lyft.com/mobile/start& when the user is not logged-in, and this page is the one that is being scored.

**Comment by dandv** [comment]
Yep, redirecting is a problem. You need to sign up, then run Lighthouse with those cookies in the browser. Not sure there's a CLI solution for this?

**Comment by juliantoledo** [comment]
It sounds like they should offer a better experience before the user sign up.

**Comment by juliantoledo** [comment]
fixed the manifest url change manually, I had to sign in with a phone number to be able to get the manifest.
