### ISSUE TITLE
Error: FetchError: request to https://www.freecharge.in/mobile/? failed, reason: Parse Error.

### ISSUE THREAD

**Issue by PaulKinlan** [GoogleChrome/gulliver#283]
https://www.freecharge.in/mobile

has a manifest, it looks ok.  Not sure what the error means.

![image](https://cloud.githubusercontent.com/assets/45510/21119990/01972824-c0bd-11e6-9554-957d36996432.png)

**Comment by juliantoledo** [comment]
@PaulKinlan I am not sure why fetch does not get that URL.

  fetch('https://www.freecharge.in/mobile/manifest.json?v=1').then(r => r.json())
  .then(data => console.log(data))
  .catch(e => console.log('Error ' + e));

I always get:
request to https://www.freecharge.in/mobile/manifest.json?v=1 failed, reason: Parse Error
