### ISSUE TITLE
Canonicalize the URL to prevent duplicate PWA submissions

### ISSUE THREAD

**Issue by dandv** [GoogleChrome/gulliver#305]
https://pwa-directory.appspot.com/pwas/5743346702090240 - :+1: 
https://pwa-directory.appspot.com/pwas/5667346802802688 - :-1: 

Query parameters like `utm*` should be stripped, redirects should be followed etc.

**Comment by juliantoledo** [comment]
The problem here is that the manifest URL is different, that is the current primary key for PWAs.

**Comment by juliantoledo** [comment]
We will keep https://pwa-directory.appspot.com/pwas/5667346802802688, it's the one that has a working manifest

**Comment by juliantoledo** [comment]
We will Canonicalize the URL and add it to the primary key for:
https://github.com/GoogleChrome/gulliver/issues/323
