### ISSUE TITLE
no lighthouse score displayed

### ISSUE THREAD

**Issue by mpoehler** [GoogleChrome/gulliver#330]
Some PWAs don't show a lighthouse score, for example Kontaktlinsen-Preisvergleich.de, submitted yesterday, https://pwa-directory.appspot.com/pwas/5754876214640640 . The lighthouse chrome plugin shows a 100/100 score.

There are currently five other PWAs without score listed on the NEW tab.

**Comment by juliantoledo** [comment]
Hi @mpoehler thank you for reporting it, we have an issue in our lighthouse server, I will investigate further to find out why it fails for some PWAs.

**Comment by CaptainCodeman** [comment]
Seems like more and more are showing up without any score - any clue what the issue is?

**Comment by juliantoledo** [comment]
@CaptainCodeman yes, the issue is the old service that uses headless shell Chrome to run Lighthouse. We are testing a new one that should be more reliable and we should be able to deploy it this week.

**Comment by CaptainCodeman** [comment]
Excellent, thanks for the update!

**Comment by juliantoledo** [comment]
@CaptainCodeman @mpoehler We rolled out a fix that is rating more PWAs properly, it also uses Lighthouse 1.5.1. We still need to go over few ones that have not been rated.

**Comment by mpoehler** [comment]
Looks good now! Thx!
