### ISSUE TITLE
Sylaps is not up-to-date 

### ISSUE THREAD

**Issue by hthetiot** [GoogleChrome/gulliver#331]
Sylaps.com lighthouse new score should be at least 81.

Pwa link: https://pwa-directory.appspot.com/pwas/5655692627148800

How to we request an update? Is there a better way than creating issue?

**Comment by juliantoledo** [comment]
Hi @hthetiot,

We run a daily cron job that should update it. I just found that it was not run the last few days and push a fix. It just ran for it.

Cheers,
Julian

**Comment by hthetiot** [comment]
Yeah 92 \o/
