### ISSUE TITLE
Submission failing

### ISSUE THREAD

**Issue by aarongustafson** [GoogleChrome/gulliver#337]
I tried adding my book via [the form](https://pwa-directory.appspot.com/pwas/add) using it’s [manifest URL](https://adaptivewebdesign.info/1st-edition/read/manifest.json) and keep getting the following error:

> Error: TypeError: Parameter "url" must be a string, not undefined.

The manifest is checking out as valid and Lighthouse isn’t throwing errors either. Not sure what the cause is.

**Comment by PaulKinlan** [comment]
My first inclination is to say that I was under the impression that the start_url was a relative URL because it uses manifest url and the document url to work out what the actual start_url is.

Also, minor point, your "Scope" attribute should be "scope" (but I don't believe that this sorts the problem)

**Comment by aarongustafson** [comment]
Ah, I’ll look into it. Thanks!

**Comment by aarongustafson** [comment]
Ok, so I made the suggested tweaks and also ran it through [the validator](https://manifest-validator.appspot.com/) and it comes back clean. Still getting that same error.

**Comment by juliantoledo** [comment]
Node fetch of https://adaptivewebdesign.info/1st-edition/read/manifest.json
is not handling the protocol upgrade and we are not getting the manifest:
{
	"url": "https://adaptivewebdesign.info/1st-edition/read/manifest.json",
	"status": 200,
	"statusText": "OK",
	"headers": {
		"_headers": {
			"date": ["Thu, 09 Mar 2017 16:40:43 GMT"],
			"server": ["Apache/2.4.25 (Ubuntu)"],
			"upgrade": ["h2"],
			"connection": ["Upgrade, close"],
			"last-modified": ["Thu, 09 Mar 2017 15:09:18 GMT"],
			"etag": ["\"4d0-54a4da105c380\""],
			"accept-ranges": ["bytes"],
			"content-length": ["1232"],
			"content-type": ["application/json"]
		}
	},
	"ok": true,
	"body": {
		"_readableState": {
			"objectMode": false,
			"highWaterMark": 16384,
			"buffer": {
				"head": null,
				"tail": null,
				"length": 0
			},
			"length": 0,
			"pipes": null,
			"pipesCount": 0,
			"flowing": null,
			"ended": true,
			"endEmitted": false,
			"reading": false,
			"sync": false,
			"needReadable": false,
			"emittedReadable": true,
			"readableListening": false,
			"resumeScheduled": false,
			"defaultEncoding": "utf8",
			"ranOut": false,
			"awaitDrain": 0,
			"readingMore": false,
			"decoder": null,
			"encoding": null
		},
		"readable": true,
		"domain": null,
		"_events": {},
		"_eventsCount": 1,
		"_writableState": {
			"objectMode": false,
			"highWaterMark": 16384,
			"needDrain": false,
			"ending": true,
			"ended": true,
			"finished": true,
			"decodeStrings": true,
			"defaultEncoding": "utf8",
			"length": 0,
			"writing": false,
			"corked": 0,
			"sync": true,
			"bufferProcessing": false,
			"writecb": null,
			"writelen": 0,
			"bufferedRequest": null,
			"lastBufferedRequest": null,
			"pendingcb": 0,
			"prefinished": true,
			"errorEmitted": false,
			"bufferedRequestCount": 0,
			"corkedRequestsFree": {
				"next": null,
				"entry": null
			}
		},
		"writable": false,
		"allowHalfOpen": true,
		"_transformState": {
			"needTransform": false,
			"transforming": false,
			"writecb": null,
			"writechunk": null,
			"writeencoding": null
		}
	},
	"bodyUsed": false,
	"size": 0,
	"timeout": 0,
	"_raw": [],
	"_abort": false
}

**Comment by aarongustafson** [comment]
So I guess the protocol upgrade is an issue on the Node service’s end? Is there anything I can do?

**Comment by juliantoledo** [comment]
@aarongustafson yes, the issue is in Node service’s end, I tried few things and did not make much progress, I will try to fix it soon.

**Comment by juliantoledo** [comment]
I was able to add support for it by adding a spdy agent #414
