### ISSUE TITLE
Some apps does not show lighthouse score

### ISSUE THREAD

**Issue by tezhub** [GoogleChrome/gulliver#368]
I just read in other issue it just takes 1min to generate lighthouse score. These PWA's are added a day ago but still no lighthouse info generated.
- https://pwa-directory.appspot.com/pwas/5676600884461568#t=Linklet%20App&bg=%233f51b5&c=%23ffffff
- https://pwa-directory.appspot.com/pwas/6230263776411648#t=Nerfed%20News&bg=%233f51b5&c=%23ffffff
- https://pwa-directory.appspot.com/pwas/5655274761224192#t=aiueO&bg=%23ffffff&c=%23000000

Just reporting if its some kind of bug mentioned in #330

And FYI the PWA that was added just now https://pwa-directory.appspot.com/pwas/4846515507953664#t=Mixcloud%20-%20Radio%20%26%20DJ%20mixes&bg=%23ffffff&c=%23000000 got the score.

**Comment by juliantoledo** [comment]
Hi @tezhub, thank you for reporting those. I had to run their tasks manually to fix them, I need to check why sometimes the first tasks fails.
