### ISSUE TITLE
Some PWA shows a variation on the score even with no changes.

### ISSUE THREAD

**Issue by vitormalencar** [GoogleChrome/gulliver#385]
I have recently observed some variations in the score even without making one change.

In this month for example my [PWA](https://pwa-directory.appspot.com/pwas/5168969224814592#t=Vitor%20Alencar&bg=%23462373&c=%23ffffff) score fell to 45 even the lighthouse scoring 100 when I run the tests.

<img width="604" alt="captura de tela 2017-05-04 as 23 17 43" src="https://cloud.githubusercontent.com/assets/7741167/25731806/05841d24-3120-11e7-9792-565279f40f9a.png">

<img width="1001" alt="captura de tela 2017-05-04 as 23 16 46" src="https://cloud.githubusercontent.com/assets/7741167/25731836/372e3a3a-3120-11e7-8589-852a5dee2f51.png">

I noticed that this happened with other projects as well.

**Comment by juliantoledo** [comment]
@vitormalencar Thank you for letting us know.

We are rolling out LH v1.6.5, that should help improve our scoring, I will also manually check your PWA to find out what bug we may have.

**Comment by andreban** [comment]
Investigating this. The report says it doesn't register ServiceWorker, and that's there's no Manifest, which the page clearly has (and it shows when running lighthouse locally) 

<img width="612" alt="screen shot 2017-05-05 at 9 35 11 am" src="https://cloud.githubusercontent.com/assets/1733592/25738656/360685c6-3176-11e7-9660-92d3a22c1108.png">

**Comment by juliantoledo** [comment]
I ran it again for this PWA and it hits a 100. There must be a intermittent network/server problem when we run lighthouse for it.

@vitormalencar Could you please check if you have any 4XX or 5XX errors for your manifest file on your Web server?

**Comment by vitormalencar** [comment]
Thanks for the quick response guys,
I host my site on github pages, and unfortunately I guess they do not provide any logs but I checked the github uptime and did not even see a downtime on their server last month.

I have a great interest in helping with the project, so if you have something I can help let me know. 😄

**Comment by juliantoledo** [comment]
@vitormalencar we updated to Lighthouse v1.6.5 and it seems more stable when running in our VMs. We also recently added WebPageTest and PageSpeedInsight information.

I will close this one for now, please ping us if you see big spikes again.

Cheers,
Julian.

**Comment by vitormalencar** [comment]
@juliantoledo Awesome, this new update is fantastic, centralizing the information is something I always wanted 😄  awesome works guys !

I know that probably this Issue is not the best place to report but I noticed just two little weird things.


1) when entering the url that I had saved in my browser the page shows two headers

![captura de tela 2017-05-12 as 18 25 42](https://cloud.githubusercontent.com/assets/7741167/26017663/25e44f72-3741-11e7-8eeb-bb3d8193a60f.png)

2) When I change the zoom of the navigator the buttons are without style. I tested it on other browsers and this seems to be just in chrome.

![captura de tela 2017-05-12 as 18 26 38](https://cloud.githubusercontent.com/assets/7741167/26017673/2f56948e-3741-11e7-8a26-3d4af5725c68.png)

**Comment by juliantoledo** [comment]
@vitormalencar thank you for reporting these two, I opened a bug for the double header issue, the link should work if you remove the anchor tag from the URL:
https://github.com/GoogleChrome/gulliver/issues/403

**Comment by vitormalencar** [comment]
@juliantoledo my chrome version is `58.0.3029.110 (64-bit)` on mac OS, 

I also tried removing all of the extensions that I have installed to make sure they were not interfering with the page.

The button changes when I zoom out/in the page
