### ISSUE TITLE
in-app back button behaves as browser's back button

### ISSUE THREAD

**Issue by mcmd** [GoogleChrome/gulliver#419]
If one searches for "progressive web apps directory" in google.com and clicks in a site link (like https://pwa-directory.appspot.com/pwas/5659043372728320 ) the arrow on the top left corner behaves as the the browser's back button, taking the user back to google.com results, instead of to the list of PWAs

**Comment by andreban** [comment]
We can do:
```
if (!document.referrer.startsWith(document.location.origin)) {
  router.navigate('/');
  return;
}
...
```

**Comment by mcmd** [comment]
SGTM
