### ISSUE TITLE
Doubt 

### ISSUE THREAD

**Issue by Joel-hanson** [GoogleChrome/gulliver#423]
I get a 99.5 average in my desktop for my desktop but in the site a 55 why is it so.

**Comment by Joel-hanson** [comment]
My url is joelhanson.ml

**Comment by juliantoledo** [comment]
Hi @Joel-hanson 

We are running a version of Lighthouse in a docker VM, unfortunately since we moved to LH 2+ we are facing a lot of variation when running it in this environment. Last night your site hit 100, we will investigate further to try to make the metric more stable.

Cheers,
Julian.

**Comment by Joel-hanson** [comment]
thanks @juliantoledo
