### ISSUE TITLE
Improve pwa.js

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#63]
- [x] Switch to numeric error codes
- [x] Make object oriented
- [x] Add jsdoc
- [x] Add tests

**Comment by juliantoledo** [comment]
Great ideas and very needed 👍

**Comment by juliantoledo** [comment]
Added jsdocs #127

**Comment by juliantoledo** [comment]
I added one test at #128, I will use the same format to test the rest of the functions.

**Comment by juliantoledo** [comment]
@ithinkihaveacat should we switch to numeric error codes?

**Comment by ithinkihaveacat** [comment]
@juliantoledo I don't really know what best practice is… I'd feel better about testing for error codes rather than strings in tests though. What other considerations are there?
