### ISSUE TITLE
Fallback to page metadata for PWA description

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#70]
Fallback to page metadata when PWA description is missing from the manifest

if the description is not available in the manifest, we will fetch the URL referenced on start_url and extract the information from <meta name="description" content="..." />

**Comment by andreban** [comment]
So, if the description is not available in the manifest, we will fetch the URL referenced on `start_url ` and extract the information from `<meta name="description" content="..." />`

**Comment by juliantoledo** [comment]
@andreban yes, exactly.
