### ISSUE TITLE
Add Pagination support

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#72]
We need to add pagination support

**Comment by andreban** [comment]
I was looking at pagination using gcloud. It seems that finding out the number of pages [may be tricky](http://www.shiftedup.com/2015/03/08/how-to-count-all-entries-of-a-given-type-in-the-app-engine-datastore) using cloud-datastore. I'm not really happy with any solutions given in the article.

I've fixed the existing "More" button. We may need to add a "Previous Page".

**Comment by andreban** [comment]
I think we should migrate pagination to use skip / limit and if the database grows enough that it starts being an issue, we change? WDYT? @juliantoledo @ithinkihaveacat

**Comment by andreban** [comment]
Changed to skip / limit on #160

**Comment by andreban** [comment]
Closed by #160, improved by #161

**Comment by andreban** [comment]
Closed on #160 and #161. UI update being tracked on #141
