### ISSUE TITLE
Switch templating format to handlebars

### ISSUE THREAD

**Issue by andreban** [GoogleChrome/gulliver#8]

**Comment by ithinkihaveacat** [comment]
React might be an interesting option here too.

**Comment by ithinkihaveacat** [comment]
Some pros and cons of different templating systems (following offline discussion with @andreban):

* Jade
  * Pro: already in place.
  * Con: unfamiliar (and disliked?) syntax? Not widely used.
* Mustache (Handlebars)
  * Pro: popular, familiar, simple.
  * Con: no databinding.
* Polymer
  * Pro: some usage by PWAs ([Konga](https://kongax.konga.com)).
  * Con: more than just templates, rarely rendered server-side (?).
* React
  * Pro: very popular, especially by people implementing PWAs ([Flipkart](https://www.flipkart.com), [Selio](https://www.selio.com), [NFL Now](https://www.nfl.com/now)).
  * Con: more than just templates, difficult to render server-side (?).

**Comment by juliantoledo** [comment]
Mustache works very well for AMP pages, I think it fits what we need at the beginning. I only added Jade temporarily to get us started, but I prefer not to use it.

Let me read more about React to find out more about if it can handle server-side and how.

**Comment by andreban** [comment]
I'm looking into handlebars. It seems that using it for including html sections into the page is not straightforward.

**Comment by andreban** [comment]
jade has actually been rebranded as pug: https://github.com/pugjs/pug

**Comment by andreban** [comment]
Fixed in #23
