### ISSUE TITLE
Distinguish between missing keys and datastore errors

### ISSUE THREAD

**Issue by ithinkihaveacat** [GoogleChrome/gulliver#81]
https://github.com/GoogleChrome/gulliver/blob/master/controllers/pwas/crud.js#L138 assumes that database errors are really more "expected" errors like PWAs that can't be found in the datastore. We should distinguish between these two states at a much lower level, such as somewhere within https://github.com/GoogleChrome/gulliver/blob/master/lib/model-datastore.js#L175, so that we can return a 500 or similar for server errors, and 404s for missing PWAs.

**Comment by andreban** [comment]
should find just return `resolve(null)` when it's a miss and `reject(err)` when it's an error?

**Comment by ithinkihaveacat** [comment]
I think `find()` is too late--it already looks like a ds error by that point. I think it needs to be fixed at `read()`.

**Comment by andreban** [comment]
Yes, I actually meant the `read` method on `model_datastore.js`.
