### ISSUE TITLE
OAuth client_id should be read from config.json 

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChrome/gulliver#83]
OAuth client_id should be read from config.json instead at:
https://github.com/GoogleChrome/gulliver/blob/master/public/js/gulliver.js#L100

**Comment by andreban** [comment]
`gulliver.js` is read from the frontend, and we're not publishing `config.json`. Looks like the best would be writing the `client_id` to gulliver.js in build time?

**Comment by juliantoledo** [comment]
True, could we add it to the template generation?

**Comment by andreban** [comment]
Hum. Should be possible to generate the .js from a template. Any input on this, @ithinkihaveacat. I added an issue for the build system on #89

**Comment by ithinkihaveacat** [comment]
I think we should generate a file like `config.js` which we arrange to load at some point and make available at e.g. `document.config`. So then `gulliver.js` could get the `client_id` from `document.config.client_id`--I don't think any values should be interpolated into the middle of the file that's mostly code, that's a bit weird.

**Comment by ithinkihaveacat** [comment]
Re `client_id` configuration, see #104.

**Comment by ithinkihaveacat** [comment]
I think #104 fixes this well enough, will close this. (Please re-open if you disagree.)
